### ISSUE TITLE
problem with Chinese

### ISSUE THREAD

**Issue by Dooy** [CodeRevolutionPlugins/GPT-3-Encoder-PHP#10]
English is no problem,
But there is a problem when switching to Chinese

$prompt = "我是 GPT-4，一款先进的自然语言生成 AI。";
echo ('Count: ' .   gpt_encode($prompt)  );

Count: 34 tokens

in reality: 19 tokens

**Comment by CodeRevolutionPlugins** [comment]
I checked in OpenAI's tokenizer and I also got 34 token for the below Chinese text:
$prompt = "我是 GPT-4，一款先进的自然语言生成 AI。";
[https://platform.openai.com/tokenizer](https://platform.openai.com/tokenizer)

**Comment by Dooy** [comment]
use node.js  with "cl100k_base" is 19 tokens

how to use "cl100k_base"?

```
import { get_encoding } from '@dqbd/tiktoken'

// TODO: make this configurable
const tokenizer = get_encoding('cl100k_base')

export function encode(input: string): Uint32Array {
  return tokenizer.encode(input)
}
console.log(encode('我是 GPT-4，一款先进的自然语言生成 AI。').length)
```

**Comment by CodeRevolutionPlugins** [comment]
cl100k_base is not yet supported, I added this to my todo list, will check on it and work on it.
