### ISSUE TITLE
Hundreds of MB of error_log output

### ISSUE THREAD

**Issue by mavrosxristoforos** [CodeRevolutionPlugins/GPT-3-Encoder-PHP#13]
First of all, thank you for sharing this excellent piece of code.
While using it, the following problem came up.

File `gpt3-encoder.php`  ends with the lines:

    401: $prompt = "Many words map to one token, but some don't: indivisible. Unicode characters like emojis may be split into many tokens containing the underlying bytes: 🤚🏾 Sequences of characters commonly found next to each other may be grouped together: 1234567890";
    402: $token_array = gpt_encode($prompt);
    403: error_log('Token array: ' . print_r($token_array, true));
    404: error_log('Count: ' . count($token_array));
    405: $original_text = gpt_decode($token_array);
    406: error_log('Original text: ' . $original_text);

Including this file always runs the above lines. This means that on every run, it encodes, decodes and logs out useless information in the PHP error_log file. After a few months of using this file on my localhost caused many MBs of error log output which accidentally came to my attention.

Instead of including them in `gpt3-encoder.php`, these lines should probably be moved to a `usage-example.php` file, or something like that. Thank you for the attention!

**Comment by CodeRevolutionPlugins** [comment]
Oh, right, I added in the encoder also an example. My bad, sorry!
