### ISSUE TITLE
The result of gpt_encode for Chinese characters may not be correct

### ISSUE THREAD

**Issue by planetoid** [CodeRevolutionPlugins/GPT-3-Encoder-PHP#3]
The expected result was generated by the OpenAI API tokenizer ( https://platform.openai.com/tokenizer ) , while the actual result was produced by the gpt_encode function.

Wrong cases:

- `一天一蘋果，醫生遠離我！` Expected: 25, Actual:  24
- `一天一蘋果，醫生遠離我` Expected: 22, Actual:  21
- `一天一蘋果 醫生遠離我` Expected: 19, Actual:  18
- `一天一蘋果，醫生遠離我 apple a day keeps the doctor away` Expected: 29, Actual:  28

Correct cases:
- `蘋果` Expected: 6, Actual:  6

**Comment by CodeRevolutionPlugins** [comment]
Thank you for highlighting this issue, it should be fixed now in latest update.
