### ISSUE TITLE
Extremely slow and causing time-outs?

### ISSUE THREAD

**Issue by inpresif** [CodeRevolutionPlugins/GPT-3-Encoder-PHP#7]
Hi,

Thanks again for the script.

I do have an issue though, it seems to be very slow and causing our scripts to time-out even after increasing time-out to 120 seconds on a 200 row array loop. We count tokens for each array value of max 200-500 words or so.

When we turned the script/checks off, our scripts ran within 2-4 seconds. Is this a known issue? Anything we can do to help troubleshoot and see what is lagging, and where?

Cheers.

**Comment by CodeRevolutionPlugins** [comment]
Not happening on my part, please send me an example text which is lagging for you and I check on this.
