### ISSUE TITLE
[suggest] Any plan to implement GPT-4 encoder

### ISSUE THREAD

**Issue by planetoid** [CodeRevolutionPlugins/GPT-3-Encoder-PHP#9]
I noticed that the token count differs between GPT-3 and GPT-4. Is there any plan to develop a GPT-4 encoder in PHP?

Python example: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

Thank you for your time.

**Comment by CodeRevolutionPlugins** [comment]
Idea noted, thank you. Will think on how to do this.
